"""Skip/drop tool policy for the observer.

Two distinct policies:
- ``skip_tools`` — DISCARD the event (it never reaches the turn body). Default:
  WebSearch/WebFetch (network results are noise, not memory).
- ``drop_tools`` — DISCARD the event entirely, not just redact it. Default:
  Read/Bash — their content is entirely secret (the "stronger than claude-mem"
  claim only holds if Read/Bash content is covered; redaction alone cannot
  guarantee it).

Pure functions — the policy is a deterministic allowlist, configurable per
vault via the ``[observe]`` section.
"""

from __future__ import annotations

from collections.abc import Collection

DEFAULT_SKIP_TOOLS: frozenset[str] = frozenset({"WebSearch", "WebFetch"})
DEFAULT_DROP_TOOLS: frozenset[str] = frozenset({"Read", "Bash"})

# Synthetic user turns injected by the harness: Claude Code delivers
# background-task completions as user_prompt_submit events whose WHOLE prompt
# is the wrapper (verified 2026-09-08 against a live queue — 18 episodes with
# the literal subject "<task-notification>" clustered and distilled into a
# vacuous consolidated note). Prefix checked on the prompt's first line only;
# a prompt that merely MENTIONS a tag is user content. Not configurable: these
# are harness-generated by definition, a per-vault override would only
# reintroduce noise. Extend on evidence (new injection family → new prefix).
SYNTHETIC_PROMPT_PREFIXES: tuple[str, ...] = (
    "<task-notification>",
    "<system-reminder>",
    "<local-command-stdout>",
    "<local-command-stderr>",
)


def should_skip_event(
    tool_name: str, *, skip_tools: Collection[str] = DEFAULT_SKIP_TOOLS
) -> bool:
    """True iff the event for ``tool_name`` should be discarded (not rendered)."""
    return tool_name in skip_tools


def should_drop_event(
    tool_name: str, *, drop_tools: Collection[str] = DEFAULT_DROP_TOOLS
) -> bool:
    """True iff the event for ``tool_name`` should drop the whole turn."""
    return tool_name in drop_tools


def is_synthetic_prompt(prompt: str) -> bool:
    """True iff the prompt is a harness injection (first line opens a known tag)."""
    first_line = prompt.lstrip().split("\n", 1)[0].lstrip()
    return first_line.startswith(SYNTHETIC_PROMPT_PREFIXES)


__all__ = [
    "DEFAULT_SKIP_TOOLS",
    "DEFAULT_DROP_TOOLS",
    "SYNTHETIC_PROMPT_PREFIXES",
    "should_skip_event",
    "should_drop_event",
    "is_synthetic_prompt",
]
