-- 009_supersedes_reason.sql — adds the portable supersedes_reason column to
-- storage.
--
-- Adds supersedes_reason TEXT to episodes + episode_index. The Episode model
-- carried this field as model+wire only; this migration persists it and wires
-- it into the insert/read paths and the sidecar rebuild_all episode_index upsert.
--
-- Idempotency: SQLite ALTER TABLE ADD COLUMN has no IF NOT EXISTS and cannot be
-- made conditional in raw SQL (executescript is non-procedural). The primary
-- idempotency mechanism is the migration runner's schema_version row (each NNN
-- runs at most once per DB). (001-008 use CREATE TABLE/INDEX IF NOT EXISTS as
-- defense-in-depth; ALTER cannot, so the runner is the sole guard here —
-- consistent with how 001-008 idempotency truly works, since CREATE...IF NOT
-- EXISTS alone does not insert the version row.)
--
-- Atomicity: the runner wraps each migration (DDL + the schema_version INSERT)
-- in a single BEGIN/COMMIT transaction. This file therefore carries no
-- BEGIN/COMMIT of its own (which would nest-fail inside the runner's
-- transaction): the two ALTERs are atomic with each other and with the version
-- row — if either ALTER or the INSERT fails, nothing commits and re-running
-- retries the whole migration. This closes the residual gap this header used
-- to document (DDL commits but the version INSERT fails -> re-run raises
-- "duplicate column name").
--
-- No CHECK: the field is a free TEXT enum string
-- (contradiction/correction/merge/revalidation/decay); enum enforcement is at
-- the Pydantic model (SupersedesReason in frontmatter/schema.py), not storage.
ALTER TABLE episodes ADD COLUMN supersedes_reason TEXT;
ALTER TABLE episode_index ADD COLUMN supersedes_reason TEXT;
